version: "3"

services:

  service:
    image: hello-world
    container_name: hello-world
    build:
      context: .
      args:
        ARTIFACT: hello-world
        GIT_URL: https://github.com/radimih/java-hello-world.git

    ports:
      - 80:8080
    depends_on:
      - db

  db:
    image: mysql
    container_name: hello-world-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:

  mysql-db:
